### PR TITLE
Adding functionality to destroy/remove element

### PR DESCRIPTION
**Pull request by Abijeet**
IckleChris/jquery-date-dropdowns#1

### CODE REVIEW

**Comment by IckleChris** [comment]
Thanks for this. I'm going to leave `destroy()` out of the demo, so if that's removed I'll merge this in.

**Comment by Abijeet** [comment]
@IckleChris  - Done.

**Comment by AbijeetP** [comment]
@IckleChris  - You may have to generate the min file again. I didn't do that!

**Comment by IckleChris** [comment]
@AbijeetP Done!

**Pull request merged**
